version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: traceassist-postgres
    environment:
      POSTGRES_USER: traceassist_user
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: traceassist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: