apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceassist-backend
  namespace: traceassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceassist-backend
  template:
    metadata:
      labels:
        app: traceassist-backend
    spec:
      containers:
        - name: traceassist-backend
          # IMPORTANT: Update this with the path to your production image
          image: your-registry/traceassist-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # This section tells Kubernetes to create an environment variable
            # named DATABASE_URL inside the container.
            - name: DATABASE_URL
              valueFrom:
                # It gets the value from the secret named 'postgres-secret'.
                secretKeyRef:
                  name: postgres-secret
                  # It uses the key 'DATABASE_URL' from that secret.
                  key: DATABASE_URL

