apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceassist-backend
  namespace: traceassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceassist-backend
  template:
    metadata:
      labels:
        app: traceassist-backend
    spec:
      serviceAccountName: traceassist-sa
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
        - name: traceassist-backend
          image: traceassist-backend:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
          env:
            # --- This section is restored to your original, working version ---
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: ENCRYPTION_KEY
            # --- This is the only new section, for the Grafana token ---
            - name: GRAFANA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafana-api-secret
                  key: GRAFANA_API_TOKEN
          ports:
            - containerPort: 8000
