apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceassist-frontend
  namespace: traceassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceassist-frontend
  template:
    metadata:
      labels:
        app: traceassist-frontend
      annotations:
        instrumentation.opentelemetry.io/inject: "true"
    spec:
      serviceAccountName: traceassist-sa
      containers:
        - name: traceassist-frontend
          image: traceassist-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "https://ingest.in.signoz.cloud:4317"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "Authorization=Bearer 82b0858a-0573-4057-9848-01b6f0733956"
          ports:
            - containerPort: 5173
