apiVersion: v1
kind: Secret
metadata:
  name: grafana-api-secret
  namespace: traceassist
type: Opaque
stringData:
  # The token you generate from the Grafana UI
  GRAFANA_API_TOKEN: "" 
  
  # NEW: Grafana URLs are now managed here
  # The internal URL for the backend to communicate with Grafana inside the cluster
  GRAFANA_API_URL: "http://grafana.grafana.svc.cluster.local:80"
  
  # The external URL for the user's browser to view the embedded panels
  GRAFANA_PUBLIC_URL: "http://localhost:3000"