apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: traceassist
type: Opaque
stringData:
  # This is the connection string your backend application will use.
  # It tells the backend how to find the PostgreSQL database you just started with Docker Compose.
  #
  # - postgresql://        : The standard protocol for PostgreSQL connections.
  # - traceassist_user     : The username you defined in docker-compose.yaml.
  # - your_strong_password : The password you defined in docker-compose.yaml.
  # - host.docker.internal : A special DNS name that Docker provides for containers to connect
  #                          to the host machine. This works on Docker Desktop for Mac and Windows.
  # - 5432                 : The port you exposed in docker-compose.yaml.
  # - traceassist_db       : The database name you defined in docker-compose.yaml.
  #
  DATABASE_URL: "postgresql://traceassist_user:your_strong_password@host.docker.internal:5432/traceassist_db"
  ENCRYPTION_KEY: "TCyg-3Dme7oVPtgOIikG4Msxj2AYrSG9-7DKzYqAM6g="
