apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: traceassist
type: Opaque
stringData:
  # This special DNS name allows the pod inside Minikube to connect to the database
  # running on your local machine via Docker Compose.
  DATABASE_URL: "postgresql://traceassist_user:your_strong_password@host.minikube.internal:5432/traceassist_db"